### ISSUE TITLE
Traditional Chinese translation

### ISSUE THREAD

**Issue by liuliuOD** [dair-ai/Prompt-Engineering-Guide#120]
Although there is already a Simplified Chinese translation in this project, there are some differences in terminology compared to Traditional Chinese. Would it be feasible to add a Traditional Chinese translation?

If answer is true, I would like to contribute.

**Comment by omarsar** [comment]
@Puntua Thanks for your interest in helping with translation. To translate the content into Spanish, you can simply create a `tcn-pages` folder in the root. You can then translate all the `<>.en.mdx` files found in the `pages` folder and make sure to keep the same folder structure in your `tcn-pages` folder. In other words, don't touch the `pages` folder since your translated files will all be in the `tcn-pages` folder. Once you finish with the translations, you can submit PR and I will take care of integrating it into the website. Does this work for you?

I suggest also using a grammar tool that works for your language to make sure grammar is consistent and avoid spelling errors in your translations. It's preferred if you can translate from the English docs because they are always up to date. Looking forward to your contributions and thanks a lot. Let me know if you have any questions.

**Comment by liuliuOD** [comment]
@omarsar Got you. I will start to translate the content into Traditional Chinese.
Welcome anyone who want to join contribution to look [here ](https://github.com/liuliuOD/Contributor__Prompt-Engineering-Guide/tree/translate/zh-TW).

**Comment by liuliuOD** [comment]
@omarsar Should I make pull requests incrementally instead of all at once, given the frequent updates to the project to avoid significant discrepancies between the initial translation stages and the final merge?

**Comment by silopolis** [comment]
Hello friends,

Would love to have the Chinese team opinion about my TMS setup proposal here #140 :)

TY
J

**Comment by omarsar** [comment]
@liuliuOD all at once is preferred.
