### ISSUE TITLE
Translation: German 

### ISSUE THREAD

**Issue by meanwhile7** [dair-ai/Prompt-Engineering-Guide#159]
I would like to translate these repo into German. Please provide a guide to which file to translate and where to put the files as I read some open issues I didn't understand properly the guide

**Comment by omarsar** [comment]
Hi @meanwhile7 Thanks for your interest in helping with the translation. To translate the content into Catalan, you can simply create a `ge-pages` folder in the root. You can then translate all the `<>.en.mdx` files found in the `pages` folder and make sure to keep the same folder structure in your `ge-pages` folder. In other words, don't touch the `pages` folder since your translated files will all be in the `ge-pages` folder. Once you finish with the translations, you can submit PR and I will take care of integrating it into the website. Does this work for you?

I suggest also using a grammar tool that works for your language to make sure grammar is consistent and avoid spelling errors in your translations. It's preferred if you can translate from the English docs because they are always up to date. Looking forward to your contributions and thanks a lot. Let me know if you have any questions.

**Comment by meanwhile7** [comment]
ok I got it can you please assign me to this open issue

**Comment by omarsar** [comment]
any updates on this, @meanwhile7 ?

**Comment by meanwhile7** [comment]
I sincerely apologize for not actively contributing to this task and failing to unassign myself from it. Additionally, I regret not communicating my situation earlier. I acknowledge my shortcomings and apologize for any inconvenience caused by my lack of diligence.
> any updates on this, @meanwhile7 ?
